<style>
     h3 {
    color: #31968e;
    
    text-shadow: 1px 1px #000;
}
h4 {
    color: #31968e;
    
    text-shadow: 1px 1px #000;
}
h5 {
    
    color: #31968e;
    text-shadow: 1px 1px #000;
}
.bigger {
    font-family: "Arial Black, Gadget, sans-serif";
  font-size: 20px;
}

}
</style>
<br>
<br>
<p>Le programme de recherche de l'équipe EIS s'articule essentiellement autour des domaines/disciplines de recherche Smart agriculture et smart city, Génie Logiciel, Big Data et sécurité quantique. Systèmes d'aide à la décision, Intelligence Artificielle, Datamining & datawarehouse, Réseaux, E-learning, E-gouvernement, Sémantiques des données informatiques, Informatique pervasive (ubiquitous), Blockchain qui sont devenues des tendances liées, complémentaires et incontournables de nos jours.
Concernant programme de recherche de l'Équipe (2) , il est composé de neuf (09) axes dont la description et les objectifs de chacune d’elles sont présentées comme suit :
</p>
<h3>Axe 1: Software-Defined Networking SDN: IoT integration and improvement </h3>
<p>L’internet des objets (ou IoT pour internet of things et les vanets) sont actuellement au centre de l’attention des chercheurs scientifiques. La promesse d’un monde avec beaucoup plus d’objets connectés offre d’innombrables opportunités en tant qu’utilisateur et aussi chercheur.
Participer à l’amélioration des performances de ces réseaux, en s'adaptant aux nouveaux concepts SDN. Apporter une meilleure sur la disponibilité de ces réseaux et l’adaptation de ces objets connectés aux différentes contraintes de services imposées par les utilisateurs finaux, sont nos objectifs.
</p>
<h3>Axe 2 : Solutions smart parking basées sur IoT et d’autres données externes</h3>
<h4>1.DESCRIPTIF</h4>
<p>Le smart parking est un élément phare de smart city. Il rentre dans le cadre des solutions innovantes pour smart city.
La congestion du trafic représente un problème majeur pour les grandes villes urbaines. Les travaux antérieurs ont montré que la congestion du trafic sur certaines artères est en grande partie due au temps plus ou moins prit par certains automobilistes à la recherche de places de stationnement sur voirie. Cette congestion se révèle avoir plusieurs conséquences environnementales (pollution, bruit …), sociales et économiques. Pour remédier à ce fléau, on souhaite mettre en place des solutions intelligentes associant IoT à travers les données de stationnement récoltées par les capteurs, l’intelligence artificielle ainsi que des sources de données externes extraites de diverses sources pour prédire l’occupation et la disponibilité des places de stationnement. On vise à ce que ces solutions contribuent à une meilleure mobilité urbaine et des déplacements plus écologiques.
Une prédiction efficace et fiable est la base d’une gestion intelligente et efficace des places de parkings sur voirie qui facilitera la recherche des places de stationnement et le désencombrement des routes urbaines.
Dans la perspective d’apporter notre contribution dans l’amélioration de cette prédiction en particulier et la diminution de la congestion en milieu urbaine en général, nos travaux actuels se basent sur l’optimisation des modèles deep Learning avec notamment l’utilisation d’une architecture hybride associant les réseaux de neurones convolution et les réseaux de neurones récurrents avec ses variantes GRU et LSTM pour extraire dans nos données d’avantages d’informations qui contribuent à l’amélioration de la prédiction.

<h4>2.OBJECTIF</h4>
Mettre en place des solutions intelligentes temps réel de gestion de parking en utilisant les données IoT accouplé avec d’autre données externes extraite de diverses sources afin d’orienter les conducteurs vers les zones offrant des parkings libres contribuer ainsi à l’allégement de la congestion et à la diminution des émissions des gaz à effet de serre.
<h3> Axe 3: La sécurité quantique</h3>
Dans le cadre de nos activités de recherche scientifique, nous avons été amenés à travailler sur différents axes du cyber sécurité pour protéger les machines, les serveurs, les appareils mobiles, les systèmes électroniques, les réseaux et les données contre les attaques malveillantes. Ces axes peuvent être divisés en plusieurs catégories.
<ul><li>	La sécurité réseaux classique : proposer des solutions pour protéger le réseau informatique contre les intrus, qu'il s'agisse d'attaques ciblées ou de malwares opportunistes.
</li><li>	 La sécurité du réseau quantique : proposer des nouveaux protocoles pour la distribution quantique des clés, ainsi analyser les stratégies d’attaque quantiques.
</li><li>	La sécurité des applications : développer des solutions pour protéger les logiciels et les appareils contre les menaces.
</li><li>	  La sécurité des informations : garantir l'intégrité et la confidentialité des données, en se basant sur des solutions cryptographiques classiques et quantiques.

</li><li>	  La cyber sécurité quantique pour les IoT : On se basant sur notre expérience dans le domaine de la sécurité quantique on s’intéresse à l’étude de l’apport et de l’application de la sécurité quantique dans les objets connectés dans la perspective d’élaborer des solutions efficaces.
</li></ul>
<h5>Mots clés : </h5>
Cybersécurité, sécurité informatique, sécurité réseau, stratégies d’attaques informatiques, cryptographie, protocoles de distributions de clés quantiques.
<h3>Axe 4 : Le Big Data et l'Intelligence Artificielle pour l'informatisation des services publics au Maroc</h3>
<h4>1.DESCRIPTIF</h4>
L'administration marocaine a connu de nombreuses réformes au cours de cette décennie. Des expériences innovantes ont été menées dans de nombreux domaines. Malgré ces nombreux acquis, l'action de l'administration et son mode de fonctionnement font l'objet de critiques tant de la part de ses usagers que de la part de la société civile. L'organisation, le rôle et les missions de nos administrations doivent en effet être repensés et adaptés à un contexte politique, économique et social en pleine mutation. L’administration électronique, levier et outil incontournable pour la modernisation de l’administration, constitue un enjeu majeur visant à instaurer une administration citoyenne, transparente et de proximité en vue de faciliter l'accès des usagers aux services publics et d'alléger les charges de l'administration. Dans ce sens, l’offre des services publics électroniques au Maroc s’est développée durant la dernière décennie de manière notable, notamment en ce qui concerne la mise en ligne de l’information administrative statique ou personnalisée. Les Big Data et les techniques de l’intelligence artificielle deviendront l'un des secteurs d'investissement les plus puissants pour le gouvernement. Le gouvernement électronique peut utiliser le Big Data et l’IA pour découvrir les tendances et les modèles de comportement des gens sur les réseaux sociaux afin que le gouvernement puisse fournir un service meilleur, efficace et efficient. Le terme de Big Data offre de nouvelles opportunités pour la création de valeur, la découverte, la prédiction et habiliter l'intelligence d'affaires pour l'aide à la décision dans l'e-gouvernement.
<h4>2.OBJECTIF</h4>
Ce projet a comme principaux objectifs
(1) de déterminer comment les Big Data et IA peuvent aider les gouvernements à améliorer la conception des politiques et la prestation de services en identifiant les principaux exemples d'utilisation des mégadonnées et l'Intelligence Artificielle dans le secteur public
(2) de déterminer comment évaluer les processus analytiques les plus couramment utilisés par les organismes publics pour saisir et traiter des informations à partir des données qu'ils collectent.
<h3>Axe 5: Decision support system for smart irrigation management based on remote sensing, physics- constrained machine learning models and reinforcement learning models</h3>
<h4>1.DESCRIPTIF </h4>
La population mondiale devrait atteindre 8,5 milliards d’habitants d’ici 2030, 9,7 milliards d’ici 2050 et dépasser les 11 milliards d’ici 2100. Cette croissance est alimentée par plusieurs facteurs tels que la croissance dans les pays en développement (en particulier en Afrique), l’industrialisation, l’évolution des niveaux de vie, et d’autres facteurs. Cela représente un véritable défi pour les chercheurs et les scientifiques, car il exerce une pression sur les ressources naturelles de la Terre. Ces menaces concernent non seulement les ressources non renouvelables, mais aussi les ressources naturelles renouvelables de la terre. Par exemple, l’air est pollué par les effets du changement climatique. L’eau et le sol, ainsi que d’autres ressources naturelles renouvelables, ne font pas exception à ces menaces. Aujourd’hui, la pénurie d’eau est une réalité ; même si la quantité d’eau sur terre ne change pas, la perturbation de son cycle naturel met en danger l’équilibre de nos écosystèmes. Le sol souffre également de plusieurs problèmes dus aux mauvaises habitudes agricoles causées par l’expansion urbaine, le surpâturage et les pratiques agricoles non durables. Face à cette situation grave, notre façon d’exploiter les ressources de la Terre doit être modifiée pour répondre aux demandes humaines actuelles sans compromettre la capacité des générations futures de répondre à leurs propres besoins et en même temps prendre soin de notre planète et d’atténuer les changements climatiques. Dans le cadre de ce projet, nous nous concentrons sur l’agriculture en tant qu’utilisateur clé de l’eau, du sol et de l’air afin de parvenir à une utilisation efficace et durable des ressources naturelles de la Terre. L’agriculture représente environ 70% de l’eau utilisée dans le monde. Au Maroc, l’agriculture utilise plus de 86% des ressources en eau, principalement dans les activités d’irrigation qui subissent d’énormes pertes dues à l’utilisation de techniques non optimales. Sans parler des efforts de l’État pour étendre les zones irriguées compte tenu des avantages économiques de l’agriculture irriguée. Cela exercera encore plus de pression sur ces ressources dans les années à venir. Heureusement, avec le développement rapide et la maturité des technologies telles que l’Internet des objets (IdO), les réseaux à grande vitesse, la robotique.

<h4>2.OBJECTIF</h4>
Le présent projet est consacré à l’innovation dans le domaine de la gestion durable de l’eau à l’échelle de la ferme. Il vise à développer un système novateur d’aide à la décision qui peut aider les agriculteurs à optimiser leurs pratiques agricoles telles que l’irrigation et la fertilisation, grâce à des technologies modernes afin d’améliorer l’efficacité de l’utilisation de l’eau tout en gagnant la production végétale. Pour cela, une approche innovante basée principalement sur l’utilisation combinée de la télédétection, des données multi-sources, de la modélisation de processus, des modèles ML à contraintes physiques et des modèles d’apprentissage par renforcement sera adoptée.
<h3>Axe 6 : Software engineering</h3>
La compétitivité des éditeurs de logiciels repose sur la gestion réussie de leurs projets. L'une des tâches les plus importantes et les plus difficiles dans la gestion de projet logiciel consiste à évaluer avec précision l'effort requis pour développer un produit. Fournir des estimations fiables et précises reste un objectif difficile pour les éditeurs de logiciels en raison de plusieurs facteurs, notamment le facteur humain, la diversité des projets logiciels, l'incertitude inhérente à la mesure des caractéristiques et la diversité des environnements de développement.
Ce travail de recherche vise à proposer des techniques d'apprentissage automatiques permettant l’estimation de l'effort des projets logiciel notamment dans les premiers stades du cycle de vie des logiciels.
<h3>Axe 7 : Data Science & Knowledge</h3>
Cet axe porte sur les théories et les algorithmes permettant d’extraire des connaissances à partir de données générées par les systèmes informatiques sous toutes leurs formes (massives, complexes, hétérogènes, incertaines, etc.) et leurs applications concrètes dans des domaines majeurs tels que la finance, la santé et la cybersécurité
<h3>Axe 8 : Ingénierie financière basé sur l'intelligence artificielle et blockchain</h3>
En banque comme dans d’autres industries, le champ d’utilisation de l’IA est large. Elle permet par exemple de mieux segmenter les clients, leur proposer des offres et produits sur-mesure, de détecter les fraudes, etc. Il s’agit là d’utilisations déjà mises en œuvre ou en cours de mise en œuvre.
L’aspect « boîte noire » de l’IA provoque certaines réticences auprès de certains responsables en banque ainsi qu’au niveau du régulateur qui lui préfèrent des modèles classiques plus formels et plus facilement « auditables ». Nous proposons des techniques pour faciliter l'applicabilité des algorithmes de ML afin de rassurer le management des banques et le régulateur. Pour aller plus loin : utilisation de l’IA au sein d’un nouveau paradigme, celui de la Blockchain. Lorsqu’on parle de Blockchain le premier réflexe est de penser au Bitcoin, qui est un crypto actif qui se voit comme une alternative au système monétaire actuel. La Blockchain propose en effet un nouveau paradigme, décentralisé, sans intermédiaire et dématérialisé, par opposition au système monétaire FIAT (monnaies décrétées par les États), qui est régi par les banques centrales. Les crypto actifs semblent donc s’attaquer de façon frontale aux pouvoirs régaliens monétaires et bancaires. En ce qui nous concerne, nous sommes convaincus que les crypto actifs pourront jouer un rôle complémentaire à celui de la finance traditionnelle. Nous proposons notamment aux PME et aux TPE qui sont « trop risquées » pour les banques qui refusent donc de leur octroyer un crédit, de se financer directement via un processus de digitalisation d’actifs appelé tokenisation. En effet, en tokenisation une émission de dette (sous un modèle qui s’inspire des émissions obligataires), et en l’écoulant sur une plateforme de trading de cryptoactifs, il sera plus simple pour une PME de se financer, par exemple, en fournissant une dette de 1000€ en mille token de 1€. Il suffit que mille personnes dans le monde achètent ce token pour que la PME se retrouve financée.
Pour cela, il est nécessaire de pouvoir émettre de nouveaux types d'actifs financiers, de gérer leurs risques avec des mathématiques financières et de les rendre liquides, à travers des techniques de marketing basées sur du ML.
De façon plus générale, les plateformes d'échange de crypto actifs offrent un terreau fertile d'application des mathématiques financières et de l’IA. En effet, ces plateformes sont ouvertes 24h/24 (contrairement aux marchés classiques qui ouvrent à 9h et ferment à 17h), et offrent la possibilité de récupérer via des APIs[12] et en temps réel les carnets d'ordres de crypto actifs liquides et non-liquides.
Ainsi, nous utilisons la Blockchain comme un laboratoire où nous allions Mathématiques Financières, IA et Big Data (à ce titre, nous consacrons le temps qu’il faut pour fiabiliser nos données et nos algorithmes de récupération et de stockage de celles-ci ; la qualité des données étant cruciale) et proposons nos services à toutes entreprises intéressées par nos modèles, notamment celles qui sont spécialisées dans la Blockchain et qui souhaitent bénéficier d’expertise en ingénierie financière.
L’aspect global (dans le sens mondial) des plateformes de trading de crypto actifs et le fait qu’elles tournent 24h/24, permettent aussi d’envisager la mise en place de nouvelles mesures de risque, qui s’inspirent des mesures de risque de marché et de contrepartie utilisées en banque, sauf que celles-ci présentent un aspect global et continu dans le temps inédit. En vue de la grande diversité des acteurs, des marchés financiers et des plateformes d’échange de crypto actifs, il est devenu nécessaire que les suppositions de base (sur lesquels se basent les modèles actuels) évoluent et s’adaptent à ce nouvel environnement tout en maîtrisant les risques.
<ul><li>	 Utilisation des smart contrat dans le domaine financier essentiellement le e- Crowdfunding .
</li><li>	Sécurisation des transactions financières dans le Crowdfunding .
</li><li>	 Prédiction des fraudes et blanchiment d'argent en l'intelligence artificielle et blockchain .
</li><li>	Traçabilité et transparence des paiements mobiles.</li></ul>
<h3>Axe 9 : Optimisation multi-objective des Conteneurs dans les Clouds basée sur les algorithmes méta-heuristiques et Deep Learning</h3>
Actuellement, en raison de la disponibilité du Cloud Computing, de la grande flexibilité et des économies de coûts, de nombreuses entreprises l'utilisent pour gérer à distance leur infrastructure informatique tout en déléguant sa gestion à un tiers. Cependant, les centres de données Cloud sont les plus gros consommateurs d'énergie et une grande partie de cette énergie est gaspillée en raison d'une allocation inefficace des ressources. La virtualisation est l'une des approches les plus efficaces pour améliorer la consommation d’énergie et réduire les coûts dans les centres de données. La virtualisation est l’une des approches les plus efficaces pour améliorer et optimiser les ressources, la consommation d’énergie et les coûts dans les centres de données. Par conséquent, cette thèse s’est principalement concentrée sur l’optimisation de l’allocation des ressources au niveau logiciel basé sur la technologie de conteneurisation. En effet, La conteneurisation est une technologie qui visualise les ressources matérielles dans un conteneur avec une certaine abstraction et permet de packager des applications et leurs dépendances plus efficacement en supportant plusieurs systèmes d’exploitation.
L’objectif de cet axe de recherche est de proposer une architecture et des algorithmes de placement et de migration de conteneurs, qui prennent en compte les exigences de qualité de service (QoS) des différents utilisateurs afin de minimiser la consommation d’énergie. Pour atteindre les objectifs fixés, nous allons faire appel aux algorithmes méta-heuristiques pour optimiser les ressources matérielles telles que l’algorithme génétique, ACO et d'autres méthodes d'optimisation. Ces algorithmes fournissent plusieurs solutions qui seront enregistrées dans des DataSet sur lequel nous allons l'utiliser pour effectuer l'apprentissage automatique pour produire des meilleures solutions.
</p>